# Generated by Django 4.0.4 on 2022-06-13 20:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import membre.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo_profil', models.ImageField(blank=True, upload_to=membre.models.telecharger, verbose_name='photo de profil')),
                ('addresse', models.CharField(blank=True, max_length=100, verbose_name="addresse d'habitation")),
                ('tel', models.BigIntegerField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True)),
                ('is_driver', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
