# Generated by Django 4.0.4 on 2022-06-13 20:36

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='membre.membre')),
                ('date_acquisition', models.DateField(verbose_name="Date d'acquisition du vehicule")),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('membre.membre',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
            },
        ),
        migrations.CreateModel(
            name='PointField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('etat', models.CharField(blank=True, max_length=200, null=True)),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('nbre_place', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SearchVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trouve', models.BooleanField(default=False)),
                ('depart', models.CharField(blank=True, max_length=200, null=True)),
                ('arrive', models.CharField(blank=True, max_length=200, null=True)),
                ('distance', models.FloatField()),
                ('temps', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('transport_mode', models.CharField(choices=[('foot', 'foot'), ('car', 'car'), ('train', 'train')], default='foot', max_length=100)),
                ('chemin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.pointfield')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_accepted', to='measurement.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trouve', models.BooleanField(default=False)),
                ('depart', models.CharField(blank=True, max_length=200, null=True)),
                ('arrive', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('distance', models.FloatField()),
                ('temps', models.FloatField()),
                ('transport_mode', models.CharField(choices=[('foot', 'foot'), ('car', 'car'), ('train', 'train')], default='foot', max_length=100)),
                ('chemin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.pointfield')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='membre.membre')),
                ('serch_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='measurement.itineraire')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='measurement.vehicule'),
        ),
    ]
