# Generated by Django 4.0.4 on 2022-06-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_history_serch_vehicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='serch_vehicule',
            new_name='itineraire',
        ),
        migrations.AddField(
            model_name='history',
            name='search_vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='measurement.searchvehicule'),
        ),
    ]
