# Generated by Django 4.0.4 on 2022-06-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
        ('measurement', '0003_rename_serch_vehicule_history_itineraire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='measurement.vehicule'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'acquisition du vehicule"),
        ),
        migrations.AlterField(
            model_name='history',
            name='membre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='membre.membre'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='temps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointfield',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointfield',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchvehicule',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchvehicule',
            name='temps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
