# Generated by Django 4.0.4 on 2022-06-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_driver_car_alter_driver_date_acquisition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='chemin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.pointfield'),
        ),
        migrations.AlterField(
            model_name='searchvehicule',
            name='chemin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.pointfield'),
        ),
        migrations.AlterField(
            model_name='searchvehicule',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_accepted', to='measurement.driver'),
        ),
    ]
